### ISSUE TITLE
window.require is not a function

### ISSUE THREAD

**Issue by visopsys** [ZorrillosDev/watchit-desktop#1]
I got this error while trying to run `npm run dev`. I guess this might relate to webpack but not sure how to fix it.

![Screen Shot 2021-01-11 at 4 03 46 PM](https://user-images.githubusercontent.com/510036/104252335-ab0a4700-5426-11eb-8faa-fb04a952708d.png)

**Comment by geolffreym** [comment]
Hey @visopsys..
Looks like development server open window in browser and not in electron?

**Comment by visopsys** [comment]
That's right. My bad, I did not read the README carefully 😄

**Comment by visopsys** [comment]
@geolffreym  It requires public and private keys in the login form. What is that thing?

**Comment by geolffreym** [comment]
Hi @visopsys.
You need deploy your gateway. The gateway create that keys in a dummy file. We don't have a public gateway yet, we are working on it.. you are welcome to contrib :) . Please check https://github.com/ZorrillosDev/watchit-gateway

**Comment by geolffreym** [comment]
@visopsys we have some gateways ready, let me know to help to get app running!!

**Comment by visopsys** [comment]
@geolffreym I ran the `watchit-gateway` but did not see the key files. Where are they? 

In addition, the gateway sync seems taking forever to finish.

**Comment by geolffreym** [comment]
@visopsys yep, takes lot of time cause need migrate all the movies but we have public gateway already, soo try using this public key zdpuArWADGRBPjyaDhJn8DYtSWzzEZ1icAtUFCmJHMWKFoQYF .. let me know :)

**Comment by geolffreym** [comment]
@visopsys try this `zdpuAr6kSme3uijonCn1Rg2wjjAF1Xma4ra3frkS7Kug6kvne`

**Comment by visopsys** [comment]
@geolffreym just sent you an email

**Comment by geolffreym** [comment]
Replied!!
