### ISSUE TITLE
Hangs at connecting

### ISSUE THREAD

**Issue by danrobi11** [ZorrillosDev/watchit-desktop#33]
Very nice app. Thanks!
Im running [Galacteek](https://github.com/pinnaculum/galacteek/) which does have ipfs router. Watchit does too therefore I cant run both at the same time. Watchit just hangs at connecting or resolving.

I could run the official ipfs router and disable the embedded ipfs router in Galacteek. 
How can I disable the ipfs router in Watchit and make Watchit use the official ipfs router ?

Would be handy to have that option in settings.

watchit-0.1.0-beta.3.AppImage
OS: MX 19.3 (patito feo) x86_64 based Debian GNU/Linux 10 (buster)
SysV init version: 2.93
Kernel: 4.19.0-9-amd64
Xorg v1:7.7+19
WM: Spectrwm

**Comment by xirapo** [comment]
Thanks for creating an issue and let us know the troubles you are running into with Watchit.

This is an issue with ports, Watchit runs on port 5002 if you have something running on this port please disable the application and Watchit will run without trouble.

in the next release, we are going to be adding a  port resolution pathway so this way the application does not hang on the screen without letting you know.

we are improving on this. please let us know if you find other issues so we can fix them for all the users.

**Comment by danrobi11** [comment]
> we are going to be adding a port resolution pathway

Thanks!

**Comment by geolffreym** [comment]
fixed in release 0.1.0-beta4

**Comment by danrobi11** [comment]
> fixed in release 0.1.0-beta4

Yes working now. Thank you much!
