### ISSUE TITLE
Improper display in non fullscreen

### ISSUE THREAD

**Issue by justicenode** [ZorrillosDev/watchit-desktop#34]
When one uses the app in not fullscreen the movies are still displayed like it was fullscreen and they get cut off on the right.

**Comment by xirapo** [comment]
Thanks for creating an issue @justicenode , to better understand the issue can you please share with us the OS you are using the application alongside a screenshot of the movie getting cut out by the screen or the application itself so we can fix it in the next release and you can enjoy watching movies in the application without any problems.

thanks for helping us improve

**Comment by justicenode** [comment]
Im using windows 10 home version 1909 and watchit version 0.1.0-beta.3. During playback it works fine but on the list of movies they get cut off like this:

![watchit-bug](https://user-images.githubusercontent.com/26402137/111084682-f79bfc80-8513-11eb-807e-f918594789ff.png)

If theres any additional information I can give you to help solve this just let me know.

**Comment by geolffreym** [comment]
fixed in release 0.1.0-beta4
