### ISSUE TITLE
(SOLVED) Trying the new v0.1.0-beta.8.AppImage. Initialization public key not working

### ISSUE THREAD

**Issue by danrobi11** [ZorrillosDev/watchit-desktop#54]
The initialization public key used to be on the github. I cant find it anymore.

Watchit is asking for it and that public key doesnt work anymore: QmR9f898E2Y6H4rUqUQkB5g615wht1q4fxCPfZzxA4jXaR

Therefore, cant run watchit

**Comment by geolffreym** [comment]
Hi @danrobi11 thanks for submit an issue and help us to improve.
Yeah, this is a know issue (not documented yet), would you try close the process (click in the X in the right-top) and try it again?

**Comment by geolffreym** [comment]
Issue replicated, fixing in next release!!

**Comment by geolffreym** [comment]
@danrobi11 did u could connect? i was trying to connect, take a bit but after a while i get connected

**Comment by danrobi11** [comment]
@geolffreym 

Well, that's wierd. Now it does work. Like you mentioned it does take quite long tho.
Wonder why it wasnt working. Possible that maybe the CID node was down ? 
Any how, I'll close this.
