### ISSUE TITLE
Feature Request: Language and subtitles

### ISSUE THREAD

**Issue by justicenode** [ZorrillosDev/watchit-desktop#56]
I was thinking about using this for my own movie collection but many of my movies have multiple languages and/or subtitles.

Technically one could just use the quality parameter to hack your way around that but then you would have to store the complete movie in all possible variations. It would be nice to have audio and video separated. And also subtitles would be nice.

*I might be able to implement the subtitles myself but the language one i definitely wont.*

**Comment by geolffreym** [comment]
Hi @justicenode.
What about HLS?

**Comment by justicenode** [comment]
@geolffreym from what ive read hls does support multiple audio streams but there would have to be something in the ui/player to select one specifically.
 I dont know hls very well so i dont know how you would implement that, but I would love to see that in the future.

**Comment by geolffreym** [comment]
Hey @justicenode yeah!! actually the apps supports subs selection, quality selection and audio selection with any HLS resource, so if u have your legal content available in HLS, its easy to handle it using the watchit-gateway https://github.com/ZorrillosDev/watchit-gateway/blob/master/USAGE.md

**Comment by justicenode** [comment]
@geolffreym didnt know that. Im gonna try and set up a watchit-gateway then and see if i can get it to work. Docs dont mention it and I couldnt find a movie in the public library that had multiple languages or subtitles, so I assumed it wasnt there.

**Comment by geolffreym** [comment]
@justicenode Yeah, we need add more info in the docs, maybe some features available could be great!!
