### ISSUE TITLE
Cant connect with new v0 1 0-beta 9 AppImage

### ISSUE THREAD

**Issue by danrobi11** [ZorrillosDev/watchit-desktop#58]
Stuck on bootstrap. After a while it times out and bring me back to launch screen.
When it brings me back, clicking on `connect` loops me right back:

![watchit-v0 1 0-beta 9 issue](https://user-images.githubusercontent.com/48020114/116364729-8027e100-a7d2-11eb-8981-f70a9207cf08.gif)

```
2021-04-28T08:00:45.560Z [ERROR] IPFS: Fail on start setup node
2021-04-28T08:11:56.249Z [ERROR] IPFS: Fail on start setup node
2021-04-28T08:12:01.723Z [ERROR] IPFS: Fail on start setup node
```

**Comment by geolffreym** [comment]
Hi @danrobi11 thanks for submit an issue and help us to improve.
Is this happening even after restart the app?

**Comment by danrobi11** [comment]
> Is this happening even after restart the app?

Yes

**Comment by geolffreym** [comment]
fixed in beta10 release @danrobi11
