### ISSUE TITLE
Stuck on Bootsrapping...

### ISSUE THREAD

**Issue by Zoe8338** [ZorrillosDev/watchit-desktop#60]
Im on windows 10 and the app keeps on bootsrapping after I put the Public Key

**Comment by geolffreym** [comment]
Hi @Zoe8338 is this your first time running the app? If not, are you running some service in ports 6002, 4010, 4011, 9090?

**Comment by Zoe8338** [comment]
It is the first time I am opening the app, but after you sent this comment I tried restarting and still the same thing.
I also have this info that cports shows:
https://i.imgur.com/mZEOEVl.png

**Comment by geolffreym** [comment]
Seems like a process is stuck with IPFS, would u try stopping the app and check your task manager?

**Comment by Zoe8338** [comment]
What should I look for on the task manager?

**Comment by geolffreym** [comment]
if the process is stagnant, ipfs should be shown even after closing the application

**Comment by Zoe8338** [comment]
Nothing, I just relaunched it and worked somehow! I closed some background apps I had running so maybe that fixed it?
Thank you anyways!
One last question, how do we add/(sync?) new films?

**Comment by geolffreym** [comment]
most of the time this happens it is related to a conflict with ports.
For now we provide a key containing public domain movies, but if you have content by your own you can create your own network, I invite you to know our gateway https://github.com/ZorrillosDev/watchit-gateway
